### ISSUE TITLE
breaking change 2025.1

### ISSUE THREAD

**Issue by 1mfaasj** [AlbinLind/dawarich-home-assistant#8] opened 2024-12-28 18:46 UTC
Hi, thanks for this integration! I was already experimenting the upcoming HA release (2025.1.0b2) and you're right about the warning. The integration doesnt work anymore.

`Setup failed for custom integration 'dawarich': Requirements for dawarich not found: ['dawarich-api==0.1.4'].
`

`Unable to install package dawarich-api==0.1.4: × No solution found when resolving dependencies: ╰─▶ Because dawarich-api==0.1.4 depends on pydantic<2.0.0 and pydantic==2.10.4, we can conclude that dawarich-api==0.1.4 cannot be used. And because you require dawarich-api==0.1.4, we can conclude that your requirements are unsatisfiable.
`

I'm not an expert but can it be easily fixed by just adding this value to the pyproject.toml?
`pydantic = "<2.0.0"
`

**Comment by AlbinLind** [comment] 2024-12-28 18:52
Hey thanks for checking this out. I was reading through the update notes today and realized this might be a problem.

Unfortunately it's not as simple as updating the pyproject in this repo (since hacs do not use it, but rather the manifest.json, it is there for me to have a dev environment).

I'm going to try and see if I can just release a patch that will work for both >=2025.1 and <=2024.12, by allowing both, and that everything still works. I will let you know!

**Comment by AlbinLind** [comment] 2024-12-28 20:10
I've created a [pre-release](https://github.com/AlbinLind/dawarich-home-assistant/releases/tag/0.3.2-rc1), could you try if that works for you on HA 2025.1.0b2?

You can re-download it through HACS by going to HACS, choose update information, and then choose redownload and choose (pre-release) 0.3.2-rc1. 

Please report back if that works for you :)

**Comment by 1mfaasj** [comment] 2024-12-28 21:09
Thanks for the quick action/reply! Looks like it still complains unfortunately.

The same errors I see

**Comment by AlbinLind** [comment] 2024-12-30 16:43
Could you make sure that it says `dawarich-api==0.2.0` and not `dawarich-api==0.1.4` as it did before, which is the old (non-v2 version)

**Comment by 1mfaasj** [comment] 2024-12-30 18:14
![Screenshot_20241230_191302_Home Assistant](https://github.com/user-attachments/assets/70a0d5fb-562e-4acb-80db-03f72833d12f)

**Comment by AlbinLind** [comment] 2024-12-30 19:32
Thanks, I've confirmed that 0.3.2-rc1 did in fact _not_ contain the appropriate update, I am very sorry about that. However, I've now pushed the changes to main and also created a new rc, which has the correct version. I've also tested to make sure it works on 2025.1.0b3.

I will close this issue, but if you still have issue, please re open it. And happy new years! 🎉

**Closed by AlbinLind** 2024-12-30 19:32 UTC
